# Generated by Django 5.2.3 on 2025-08-20 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=255, unique=True)),
                ("payment_id", models.CharField(blank=True, max_length=255, null=True)),
                ("signature", models.CharField(blank=True, max_length=255, null=True)),
                ("amount", models.IntegerField(default=50000)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("status", models.CharField(default="created", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
