# Generated by Django 5.2.3 on 2025-08-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="job_category",
            field=models.CharField(default="General", max_length=100),
        ),
    ]
